Bookstore: Use Redux in React components.
kessio-microverse-projects/react-bookstore pull request #3
Opened 2022-10-06 20:06 UTC by kessio

Hello 👋🏾 

The following has been implemented on this PR
- [x] Implement the concept of state management.
- [x] Use store, actions, and reducers in React.
- [x] Connect React and Redux.
- [x] Linter test has passed
- [x] Proper gitflow followed

### **Happy reviewing**

2022-10-06 20:44 UTC, omarsalem7 requested changes
Hi @kessio 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- The Pull Request has a proper title and description. ✔️
- Correct git-flow ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 20:44 UTC, omarsalem7 commented on src/redux/books/books.js
> +/* eslint-disable */
- [ ] Kindly remove this line to enable linters and try to fix them to make your code better.

2022-10-06 20:44 UTC, omarsalem7 commented on src/redux/books/booksData.js
> +/* eslint-disable */
- [ ] Also remove this line as stated before

2022-10-06 20:44 UTC, omarsalem7 commented on src/redux/categories/categories.js
> +/* eslint-disable */
- [ ] Also remove this line as stated before

2022-10-07 11:17 UTC, DammyShittu approved these changes
Hi @kessio,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 11:17 UTC, merged